[package]
name = "Assignment2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
walkdir = "2.5.0"
inquire = "0.4.0"